// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_wXa-lDTC87CUHi3Wmkq8inV3ZsiiVZs',
    appId: '1:702963451022:web:87eabb82637c096d1575df',
    messagingSenderId: '702963451022',
    projectId: 'home-5ea34',
    authDomain: 'home-5ea34.firebaseapp.com',
    storageBucket: 'home-5ea34.appspot.com',
    measurementId: 'G-PJJB42C8LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMh8GznI6rs_8_r7JzE8sacLmdGYJnr2o',
    appId: '1:702963451022:android:503de7f7a29765ae1575df',
    messagingSenderId: '702963451022',
    projectId: 'home-5ea34',
    storageBucket: 'home-5ea34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR3YCpCenBuMO9R0HR2v8k9W1oWcDaSRs',
    appId: '1:702963451022:ios:5397fe2a7da395be1575df',
    messagingSenderId: '702963451022',
    projectId: 'home-5ea34',
    storageBucket: 'home-5ea34.appspot.com',
    iosClientId: '702963451022-qc0i3ipiq5pskh31tbiourdhqp18ujrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.homework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR3YCpCenBuMO9R0HR2v8k9W1oWcDaSRs',
    appId: '1:702963451022:ios:5397fe2a7da395be1575df',
    messagingSenderId: '702963451022',
    projectId: 'home-5ea34',
    storageBucket: 'home-5ea34.appspot.com',
    iosClientId: '702963451022-qc0i3ipiq5pskh31tbiourdhqp18ujrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.homework',
  );
}
